[tool.poetry]
name = "aws-manifest-creator"
version = "0.1.0"
description = ""
authors = ["Elinor <46898565+elthorne@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^9.0.3"
boto3 = "^1.43.10"


[tool.poetry.group.dev.dependencies]
moto = "^5.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
